apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: todolist-application
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tanvanat/argocd-test.git
    targetRevision: HEAD
    path: todolist
  destination:
    server: https://kubernetes.default.svc
    namespace: todolist
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
