apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-backend
  namespace: todolist
  labels:
    app: todolist-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-backend
  template:
    metadata:
      labels:
        app: todolist-backend
      annotations:
        rollme: "{{ now | toDate | unixEpoch }}"
    spec:
      containers:
      - name: backend
        image: registry.nipa.cloud/front-test-1/tasks-api:1.0.8
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: DB_HOST
          value: "202.94.169.132"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "Tanvanat123446"
        - name: DB_NAME
          value: "todo_app"
        - name: DB_PORT
          value: "3307"

