apiVersion: v1
kind: Service
metadata:
  name: todolist-backend
  namespace: todolist
spec:
  selector:
    app: todolist-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP

