apiVersion: apps/v1
kind: Deployment
metadata:
  name: todolist-frontend
  namespace: todolist
  labels:
    app: todolist-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todolist-frontend
  template:
    metadata:
      labels:
        app: todolist-frontend
    spec:
      imagePullSecrets:
        - name: nipa-regcred
      containers:
        - name: frontend
          image: registry.nipa.cloud/front-test-1/my-app:1.0.8   # ← ใส่เลขล่าสุดเป็นจุดตั้งต้น
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000  # ถ้าเป็น Next.js/Node ใช้ 3000; ถ้า Nginx ใช้ 80

