apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: todolist
resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
